spring:
  application:
    name: business-core

  datasource:
    url: jdbc:postgresql://localhost:5432/medical_biosecurity
    username: admin
    password: password123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Clave de acceso administrativa perimetral
security:
  admin:
    secret-key: ${ADMIN_SECRET_KEY:MedicalAdmin2026!}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE