# backend/src/main/resources/application.yaml
spring:
  application:
    name: business-core
datasource:
  url: jdbc:postgresql://localhost:5432/medical_biosecurity
  username: admin
  password: password123
  driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Crea las tablas automáticamente basado en las entidades
    show-sql: true # Para que veas las consultas en la consola (útil en desarrollo)
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuración de logs para ver qué pasa con Hibernate
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
